notify:
  name: whatsapp-api-custom-notifier
  description: Send a notification using Whatsapp-api
  fields:
    message:
      name: Message
      description: The message to send
      example: 'Hello, World!'
